image: node:18.14.1

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts:
          - dist/**
    - step:
        name: Deploy artifacts using SCP to PROD
        deployment: production
        script:
          # Stop the existing server if it's running
          - ssh $DO_USER@$DO_SERVER 'pkill -f "node ./dist/server/entry.mjs"'
          # Deploy artifacts
          - pipe: atlassian/scp-deploy:0.3.3
            variables:
              USER: $DO_USER
              SERVER: $DO_SERVER
              REMOTE_PATH: 'applications/wwkuakxmsp/public_html/'
              LOCAL_PATH: 'dist/*'
          # Create .htaccess file to reverse proxy traffic
          - ssh $DO_USER@$DO_SERVER 'echo "RewriteEngine On\nRewriteRule ^(.*)$ http://127.0.0.1:4321/$1 [P,L]" > applications/wwkuakxmsp/public_html/.htaccess'
          # Start the server
          - ssh $DO_USER@$DO_SERVER 'cd applications/wwkuakxmsp/public_html/ && node ./dist/server/entry.mjs &'
