image: node:18.14.1

pipelines:
  default:
    - step:
        name: Deploy project to server and start
        deployment: production
        script:
          # Check if the server is running before stopping it
          - |
            if ssh $DO_USER@$DO_SERVER 'pgrep -f "node ./dist/server/entry.mjs"'; then
              ssh $DO_USER@$DO_SERVER 'pkill -f "node ./dist/server/entry.mjs"'
            fi
          # Clone the repository onto the server
          - git clone git@bitbucket.org:pacific-wp/astro-theme.git applications/wwkuakxmsp/public_html/
          - ls -la applications/wwkuakxmsp/public_html/
          # SSH into the server, install dependencies, build, and start the server
          - ssh $DO_USER@$DO_SERVER 'cd $DEPLOY_PATH && npm install && npm run build && node ./dist/server/entry.mjs &'
          # Create .htaccess file to reverse proxy traffic
          - ssh $DO_USER@$DO_SERVER 'echo "RewriteEngine On\nRewriteRule ^(.*)$ http://127.0.0.1:4321/$1 [P,L]" > $DEPLOY_PATH/.htaccess'
