image: node:18.14.1

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts:
          - dist/**
          - run-server.mjs  # Include the run-server.mjs file
    - step:
        name: Deploy artifacts using SCP to PROD
        deployment: production
        script:
          - pipe: atlassian/scp-deploy:0.3.3
            variables:
              USER: $DO_USER
              SERVER: $DO_SERVER
              REMOTE_PATH: 'applications/wwkuakxmsp/public_html/'
              LOCAL_PATH: 'dist/*'
          # Copy run-server.mjs to the remote server
          - scp -r run-server.mjs $DO_USER@$DO_SERVER:applications/wwkuakxmsp/public_html/
          # Execute the run-server.mjs file on the server
          - ssh $DO_USER@$DO_SERVER 'cd applications/wwkuakxmsp/public_html/ && node run-server.mjs'
