image: node:18.14.1

pipelines:
  default:
    - step:
        name: Build, install dependencies, and test
        caches:
          - node
        script:
          - npm install
          - npm run build
          # Zip the entire project folder
          - zip -r project.zip ./*
        artifacts:
          - project.zip
    - step:
        name: Deploy and start server
        deployment: production
        script:
          # Copy the zip file to the server
          - pipe: atlassian/scp-deploy:0.3.3
            variables:
              USER: $DO_USER
              SERVER: $DO_SERVER
              REMOTE_PATH: 'applications/wwkuakxmsp/public_html/'
              LOCAL_PATH: 'project.zip'
          # SSH into the server to unzip the file and proceed with deployment
          - ssh $DO_USER@$DO_SERVER 'cd applications/wwkuakxmsp/public_html/ && unzip -o project.zip && npm install && npm run build && node ./dist/server/entry.mjs'
